### ISSUE TITLE
Unable to query waiting time for requests

### ISSUE THREAD

**Issue by equadon** [inveniosoftware-contrib/kpiit#10]
Cannot use aggregate functions on Requests but works fine for Incidents.

Example:
`https://cerntraining.service-now.com/api/now/v1/stats/u_request_fulfillment?sysparm_query=u_functional_element=e993ff170a0a8c0a01e036015c55c628&sysparm_avg_fields=calendar_stc`

Results:
```JSON
{
    "error": {
        "message": "Insufficient rights to query records",
        "detail": "No permission to read column(s): [calendar_stc]"
    },
    "status": "failure"
}
```

**Comment by jbenito3** [comment]
is this still a thing @equadon ?
